name: Continous Integration

on:
    pull_request:
        branches:
            - main

    push:
        branches:
            - main

jobs:
    build-and-push-docker:
        name: Build and push docker image
        # needs: build-and-test
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: shravan146/order-service
            IMAGE_TAG: build-${{ github.run_number }}

        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v3
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker image
              run: docker build -t ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} --platform linux/amd64 -f docker/production/Dockerfile .
            - name: Push Docker image to Dockerhub
              run: docker push ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
